export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    CATEGORY:"CATEGORY",
    REMOVE_SELECTED_CATEGORY:"REMOVE_SELECTED_CATEGORY",
    SELECTED_CATEGORY:"SELECTED_CATEGORY",
    LOGGEDINADMIN:"LOGGEDINADMIN",
    DASHBOARD_DATA:"DASHBOARD_DATA",
    TOAST:"TOAST"

  };